# Variables

### *Pure Python*

In [1]:
a=1
print("Type of a:",type(a))

b=1.
print("Type of b:",type(b))

Type of a: <class 'int'>
Type of b: <class 'float'>


### Type conversions

In [2]:
c=float(a)
print(c,"  type of c:", type(c))

1.0   type of c: <class 'float'>


### Lists

List of integers

In [3]:
d=[1,2,3,4]
print("Type of d:",type(d))
print(d[2]," type of an element of d:", type(d[2]))



Type of d: <class 'list'>
3  type of an element of d: <class 'int'>


List of elements of different types

In [4]:
e=[1, "1", 1.]
print("Type of d:",type(d))

for id in [0, 1, 2]:
    print(e[id],"    - type of the element", id, " of e:", type(e[id]))

Type of d: <class 'list'>
1     - type of the element 0  of e: <class 'int'>
1     - type of the element 1  of e: <class 'str'>
1.0     - type of the element 2  of e: <class 'float'>


Elements of lists can be *reassigned*

In [5]:
e[1]=2
print(e)

[1, 2, 1.0]


### Tuples

In [6]:
f=(1,2,3)
print(f, type(f))

(1, 2, 3) <class 'tuple'>


Elements of tuples *cannot be reassigned*

In [7]:
f[2]=4

TypeError: 'tuple' object does not support item assignment

### Size of lists (and tuples)

In [8]:
len(d)

4

In [9]:
g=[[1,2,3,4],[5,6,7,8]]

In [10]:
g

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [11]:
print(g[0])
print(g[1])

[1, 2, 3, 4]
[5, 6, 7, 8]


In [12]:
print(len(g))
print(len(g[0]))

2
4


### Strings

In [13]:
h='this is a string'
print(h)

this is a string


In [14]:
size=len(h)
ll=range(size)

print("Size of the string: ", size)
print("Type of ll:   ",type(ll),"\n\n")

for id in ll:
    print(id, h[id])

Size of the string:  16
Type of ll:    <class 'range'> 


0 t
1 h
2 i
3 s
4  
5 i
6 s
7  
8 a
9  
10 s
11 t
12 r
13 i
14 n
15 g


### Concatenation of lists (operator +)

In [15]:
a="Statement_1"
b="statement_2"

c=a+" and "+b
print(c)

Statement_1 and statement_2


In [16]:
a=[1,2,3]
b=[4,5]

c=a+b
print(c)

[1, 2, 3, 4, 5]


In [17]:
c=[a]+[b]
print(c)

[[1, 2, 3], [4, 5]]


### But...

In [18]:
a=1
b=2

c=a+b
print(c)

3


In [19]:
a=str(a)
b=str(b)

c=a+b
print(c)

12


In [20]:
d=tuple([1,2]+[3,4])
e=list([1,2]+[3,4])

print(d, " - type d: ", type(d))
print(e, " - type e: ", type(e))

(1, 2, 3, 4)  - type d:  <class 'tuple'>
[1, 2, 3, 4]  - type e:  <class 'list'>


### How to sum lists *element wise* (*pure* Python)

In [21]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]
c=[]

la=len(a)

for id in range(la):
    isum=a[id]+b[id]
    c.append(isum)
    
print(c)

[7, 9, 11, 13, 15]


Another method... uses the *zip* function

In [22]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]
c=[]

for ia, ib in zip(a, b):
    isum=ia+ib
    c.append(isum)
    
print(c)

[7, 9, 11, 13, 15]


What if *a* and *b* are lists of different lengths....

In [23]:
a=[1,2,3,4,5]
b=[6,7,8,9]
c=[]

for ia, ib in zip(a, b):
    isum=ia+ib
    c.append(isum)
    
print(c)

[7, 9, 11, 13]


But...

In [24]:
a=[1,2,3,4,5]
b=[6,7,8,9]
c=[]

la=len(a)

for id in range(la):
    isum=a[id]+b[id]
    c.append(isum)
    
print(c)

IndexError: list index out of range

### Sorting Python lists

In [121]:
a=list([4,3,2,1])
print("Original list: ", a)

a.sort()
print("Sorted list:   ",a)

Original list:  [4, 3, 2, 1]
Sorted list:    [1, 2, 3, 4]


# Numpy

In [25]:
import numpy as np

a=np.array([1,2,3,4,5])
print(a, "  - type of a", type(a))

[1 2 3 4 5]   - type of a <class 'numpy.ndarray'>


In [26]:
print(len(a))   # size of a

5


... but *size* is also an *attribute* of *a*

In [27]:
print(a.size)   # size is also an attribute of the array

5


The type of the array being created can be specified as the value of the keyword *dtype* of the *array* method:

In [28]:
b=np.array([1,2,3,4,5], dtype=float)
print(b)

[1. 2. 3. 4. 5.]


Note that: 

In [29]:
c=np.array([1,2,3,4,5],dtype=str)
print(c)

['1' '2' '3' '4' '5']


In [30]:
d=[1,2,3,4,5]
d_np=np.array(d, dtype=float)
print(d_np)

[1. 2. 3. 4. 5.]


In [31]:
d_int64=np.int64(d)
d_int64

array([1, 2, 3, 4, 5], dtype=int64)

### The elements of a numpy array must be of the same type

In case they are not, they are automatically converted into the appropriate type...

In [43]:
a=np.array([1,2.1,'3'])
print(a)

['1' '2.1' '3']


### Summing arrays *element wise* is very easy... (arrays must have the same size)

In [88]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

c=a+b
print(c)

[ 6  8 10 12]


### Attributes of numpy arrays

In [89]:
print("Size:  ", a.size)
print("Type:  ", a.dtype)
print("Shape: ", a.shape)

Size:   4
Type:   int32
Shape:  (4,)


In [90]:
a=np.array([[1,2,3,4],[5,6,7,8]], dtype=np.float64)
print(a)

print("\nSize:  ", a.size)
print("Type:  ", a.dtype)
print("Shape: ", a.shape)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]

Size:   8
Type:   float64
Shape:  (2, 4)


### Array methods

In [91]:
a=a.reshape(4,2)

print(a)

print("\nSize:  ", a.size)
print("Type:  ", a.dtype)
print("Shape: ", a.shape)

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]

Size:   8
Type:   float64
Shape:  (4, 2)


In [92]:
a.transpose()

array([[1., 3., 5., 7.],
       [2., 4., 6., 8.]])

In [93]:
a.flatten()

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [94]:
print("Max:  ", a.max())
print("Min:  ", a.min())
print("Mean: ", a.mean())

Max:   8.0
Min:   1.0
Mean:  4.5


### Slicing

In [83]:
a=list(range(10))   # a Python list (it is not a numpy array)
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [87]:
print(a[1:5])
print(a[5:-1])
print(a[::2])
print(a[1::2])

[1, 2, 3, 4]
[5, 6, 7, 8]
[0, 2, 4, 6, 8]
[1, 3, 5, 7, 9]
